// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Orderer with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Orderer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Orderer with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OrdererMultiError, or nil if none found.
func (m *Orderer) ValidateAll() error {
	return m.validate(true)
}

func (m *Orderer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Host

	// no validation rules for Port

	// no validation rules for Cert

	// no validation rules for MspId

	// no validation rules for Identity

	// no validation rules for ConsenterId

	if len(errors) > 0 {
		return OrdererMultiError(errors)
	}

	return nil
}

// OrdererMultiError is an error wrapping multiple validation errors returned
// by Orderer.ValidateAll() if the designated constraints aren't met.
type OrdererMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrdererMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrdererMultiError) AllErrors() []error { return m }

// OrdererValidationError is the validation error returned by Orderer.Validate
// if the designated constraints aren't met.
type OrdererValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrdererValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrdererValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrdererValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrdererValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrdererValidationError) ErrorName() string { return "OrdererValidationError" }

// Error satisfies the builtin error interface
func (e OrdererValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrdererValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrdererValidationError{}
